Repository Leets-Makers/Weeth-FE, pull requests merged in 2024-07, with the labels that each got.

#21 #8 feat: month/year 토글 생성
  src/components/Calendar/MonthlyEvent.jsx
  src/components/Calendar/ToggleButton.jsx
  src/components/Calendar/YearCalendar.jsx
  src/pages/Calendar.css
  src/pages/Calendar.jsx
Labels: Feat

#25 #23 feat: 멤버 조회 UI
  src/App.js
  src/assets/images/Property 1=BE.png
  src/assets/images/Property 1=FE.png
  src/assets/images/Property 1=MA.png
  src/assets/images/Property 1=_DE.png
  src/assets/images/Property 1=기수.png
  src/assets/images/Property 1=메일.png
  src/assets/images/Property 1=역할.png
  src/assets/images/Property 1=이름.png
  src/assets/images/Property 1=학과.png
  src/assets/images/Property 1=학번.png
  src/assets/images/Property 1=핸드폰.png
  src/components/Header/Generation.jsx
  src/components/Header/MemberHeader.jsx
  src/components/MemberName.jsx
  src/components/home/HomeMain.jsx
  src/components/mockData/mockUser.jsx
  src/pages/Member.jsx
  src/pages/MemberDetail.jsx
Labels: Feat

#28 #26 feat: 마이페이지 UI
  src/App.js
  src/assets/images/_수정.png
  src/components/Header/MyPageHeader.jsx
  src/components/Header/RightButton.jsx
  src/components/InfoInput.jsx
  src/pages/Edit.jsx
  src/pages/MyPage.jsx
Labels: Feat

#42 #41 design: 멤버 css 수정
  src/components/Calendar/CalendarHeader.jsx
  src/components/Header/TextButton.jsx
  src/components/Header/Title.jsx
  src/components/Member/Category.jsx
  src/components/Member/MemberHeader.jsx
  src/components/Member/MemberName.jsx
  src/components/mockData/mockUser.jsx
  src/pages/Member.jsx
  src/pages/MemberDetail.jsx
  src/pages/MyPage.jsx
Labels: Design

#44 #43 feat: 마이페이지 수정
  src/components/MyPage/InfoInput.jsx
  src/components/MyPage/MyPageHeader.jsx
  src/pages/Edit.jsx
  src/pages/MyPage.jsx
Labels: Feat, Design

#45 #40 design: 출석 페이지 css 작업
  .eslintignore
  src/App.js
  src/assets/images/ic_check.png
  src/assets/images/ic_warning.png
  src/components/Attendance/AttendHeader.jsx
  src/components/Attendance/AttendMain.css
  src/components/Attendance/AttendMain.jsx
  src/components/Attendance/Modal/ModalAttend.jsx
  src/components/Attendance/Modal/ModalPenalty.css
  src/components/Attendance/Modal/ModalPenalty.jsx
  src/components/Button/Button.jsx
  src/components/Button/SmallButton.jsx
  src/components/home/HomeMain.jsx
  src/pages/Home.jsx
  src/styles/theme.js
Labels: Fix, Feat, Design

#48 #46 design: 출석 모달 css 적용
  .eslintignore
  src/assets/images/ic_close.png
  src/components/Attendance/AttendMain.jsx
  src/components/Attendance/Modal/ModalAttend.css
  src/components/Attendance/Modal/ModalAttend.jsx
  src/components/Attendance/Modal/ModalPenalty.css
  src/components/Attendance/Modal/ModalPenalty.jsx
  src/components/Button/MiddleButton.jsx
Labels: Design

#53 #49 Fix: 모달 css 충돌 오류 해결
  src/components/Attendance/Modal/ModalAttend.css
  src/components/Attendance/Modal/ModalAttend.jsx
  src/components/Attendance/Modal/ModalPenalty.jsx
Labels: Fix, Design

#58 #37 feat: 캘린더 수정
  src/assets/images/dot.png
  src/components/Calendar/CalendarHeader.jsx
  src/components/Calendar/ModalMonthContent.jsx
  src/components/Calendar/MonthlyEvent.jsx
  src/components/Calendar/ToggleButton.jsx
  src/components/Calendar/YearCalendar.jsx
  src/components/Header/TextButton.jsx
  src/components/mockData/mockEventYear.jsx
  src/pages/Calendar.jsx
Labels: Fix, Feat, Design

#59 #57 design: 출석 조회 페이지 css 설정
  src/components/Attendance/AttendCheckMain.jsx
  src/components/Caption.jsx
  src/components/home/HomeMain.jsx
Labels: Design

#63 [feat] 뒤로가기 추가
  src/components/Attendance/AttendHeader.jsx
  src/components/BoardTitle.jsx
  src/components/Calendar/CalendarHeader.jsx
  src/components/Header/Header.jsx
  src/components/Header/LeftButton.jsx
  src/components/Member/MemberHeader.jsx
  src/components/MyPage/MyPageHeader.jsx
Labels: Feat

#64 #61 Feat: 회비 페이지 생성
  src/App.js
  src/assets/images/ic_receipt.png
  src/components/Dues/DueCategory.jsx
  src/components/Dues/DuesHeader.jsx
  src/components/Dues/DuesInfo.jsx
  src/components/Dues/DuesTitle.jsx
  src/components/home/HomeMain.jsx
  src/components/mockData/mockDues.jsx
  src/pages/Dues.jsx
Labels: Fix, Feat, Design

#66 #64 fix: 이미지 파일 svg로 교체
  src/assets/images/Frame 45.png
  src/assets/images/Right.png
  src/assets/images/ic_check.png
  src/assets/images/ic_check.svg
  src/assets/images/ic_close.png
  src/assets/images/ic_close.svg
  src/assets/images/ic_home_attend.png
  src/assets/images/ic_home_attend.svg
  src/assets/images/ic_home_board.png
  src/assets/images/ic_home_board.svg
  src/assets/images/ic_home_calendar.png
  src/assets/images/ic_home_calendar.svg
  src/assets/images/ic_left.svg
  src/assets/images/ic_receipt.png
  src/assets/images/ic_receipt.svg
  src/assets/images/ic_right.svg
  src/assets/images/ic_warning.png
  src/assets/images/ic_warning.svg
  src/components/Attendance/AttendMain.jsx
  src/components/Attendance/Modal/ModalAttend.jsx
  src/components/Attendance/Modal/ModalPenalty.jsx
  src/components/Dues/DuesTitle.jsx
  src/components/Header/LeftButton.jsx
  src/components/Header/RightButton.jsx
  src/components/home/HomeMain.jsx
Labels: Fix

#70 #60 design: 캘린더 재수정
  src/assets/images/Property 1=BE.png
  src/assets/images/Property 1=FE.png
  src/assets/images/Property 1=MA.png
  src/assets/images/Property 1=_DE.png
  src/assets/images/Property 1=기수.png
  src/assets/images/Property 1=메일.png
  src/assets/images/Property 1=역할.png
  src/assets/images/Property 1=이름.png
  src/assets/images/Property 1=학과.png
  src/assets/images/Property 1=학번.png
  src/assets/images/Property 1=핸드폰.png
  src/assets/images/Vector.png
  src/assets/images/_.png
  src/assets/images/_수정.png
  src/assets/images/clock.svg
  src/assets/images/date.svg
  src/assets/images/dot.png
  src/assets/images/ic_BE.svg
  src/assets/images/ic_DE.svg
  src/assets/images/ic_FE.svg
  src/assets/images/ic_MA.svg
  src/assets/images/ic_cardinal.svg
  src/assets/images/ic_department.svg
  src/assets/images/ic_dot.svg
  src/assets/images/ic_edit.svg
  src/assets/images/ic_mail.svg
  src/assets/images/ic_menu.svg
  src/assets/images/ic_name.svg
  src/assets/images/ic_phone.svg
  src/assets/images/ic_position.svg
  src/assets/images/ic_studentID.svg
  src/assets/images/ic_under.svg
  src/components/BoardTitle.jsx
  src/components/Calendar/CalendarHeader.jsx
  src/components/Calendar/MonthlyEvent.jsx
  src/components/Header/IndexButton.jsx
  src/components/Member/MemberName.jsx
  src/pages/EventDetails.jsx
  src/pages/MemberDetail.jsx
  src/pages/MyPage.jsx
Labels: Fix, Feat, Design

#73 #68 design: 게시판 글쓰기 페이지 UI 구현하기
  package-lock.json
  package.json
  src/App.js
  src/assets/images/ic_board_fileAttach.svg
  src/components/Board/PostingHeader.jsx
  src/components/Signup/RegisterStatus.jsx
  src/components/Signup/SignupHeader.jsx
  src/pages/BoardPosting.jsx
  src/pages/Signup.jsx
Labels: Design

#74 Design#35/오늘 표시 추가
  package-lock.json
  package.json
  src/components/BoardTitle.jsx
  src/components/Calendar/CalendarHeader.jsx
  src/components/Calendar/ModalMonthContent.jsx
  src/components/Calendar/MonthCalendar.jsx
  src/components/Calendar/MonthlyEvent.jsx
  src/components/Calendar/ToggleButton.jsx
  src/components/Calendar/YearCalendar.jsx
  src/components/Header/Header.jsx
  src/components/Header/TextButton.jsx
  src/components/Member/Category.jsx
  src/components/Member/MemberHeader.jsx
  src/components/Member/MemberName.jsx
  src/components/MyPage/InfoInput.jsx
  src/components/MyPage/MyPageHeader.jsx
  src/pages/Edit.jsx
  src/pages/EventDetails.jsx
  src/pages/Member.jsx
  src/pages/MemberDetail.jsx
  src/pages/MyPage.jsx
  src/styles/theme.js
Labels: Feat, Design

#80 #75 feat: 더미데이터 수정
  src/components/Calendar/MonthCalendar.jsx
  src/components/Calendar/MonthlyEvent.jsx
  src/components/Calendar/YearCalendar.jsx
  src/components/mockData/mockEventMonth.jsx
  src/components/mockData/mockEventYear.jsx
  src/pages/Calendar.jsx
  src/pages/Edit.jsx
  src/pages/MyPage.jsx
Labels: Feat, Design

#81 #79 design: 게시된 게시판 UI 구현하기
  src/App.js
  src/assets/images/ic_comment.svg
  src/assets/images/ic_install.svg
  src/assets/images/ic_reply.svg
  src/assets/images/ic_send.svg
  src/components/Board/AttachButton.jsx
  src/components/Board/BoardComment.jsx
  src/pages/Board.jsx
  src/pages/BoardPosting.jsx
Labels: Design

#82 #56 design: 로그인 페이지 UI 구현하기
  src/components/Login/LoginHeader.jsx
  src/pages/Login.jsx
Labels: Design

#84 #78 feat: home api 연결
  .env
  .eslintignore
  src/App.js
  src/components/home/HomeMain.jsx
  src/hooks/UserAPI.jsx
  src/hooks/UserContext.js
Labels: Feat

#91 #89 feat: 상세페이지 수정
  src/App.js
  src/assets/images/ic_clock.svg
  src/assets/images/ic_date.svg
  src/components/Calendar/CalendarHeader.jsx
  src/components/Calendar/ModalMonthContent.jsx
  src/components/Calendar/MonthCalendar.jsx
  src/components/Member/MemberName.jsx
  src/components/mockData/mockEventMonth.jsx
  src/components/mockData/mockUser.jsx
  src/pages/EventDetails.jsx
  src/pages/Member.jsx
  src/pages/MemberDetail.jsx
Labels: Feat

#94 feat#93/최종 기능
  .eslintignore
  src/components/Board/AttachButton.jsx
  src/components/Board/BoardComment.jsx
  src/components/Board/NoticeHeader.jsx
  src/components/Board/PostingHeader.jsx
  src/components/Board/Typing.jsx
  src/pages/Board.jsx
  src/pages/BoardPosting.jsx
  src/pages/Login.jsx
Labels: Feat

#96 #95 feat: 게시판 상세 기능 구현
  .eslintignore
  src/App.js
  src/components/Board/NoticeHeader.jsx
  src/pages/Board.jsx
  src/pages/BoardNotice.jsx
Labels: Feat

#99 #97 fix: 출석 이름 가져올 때 에러 로직 수정
  src/components/Attendance/AttendMain.jsx
Labels: Fix

#101 #98 design: 회원가입 정보 입력 프로필 페이지 UI 구현(기능까지)
  src/components/Signup/RoleSector.jsx
  src/components/Signup/SignupHeader.jsx
  src/components/Signup/SignupMemInput.jsx
  src/components/Signup/SignupTextComponent.jsx
  src/components/Signup/SignupWhite.jsx
  src/components/home/HomeMain.jsx
  src/pages/Profile.jsx
  src/pages/Signup.jsx
Labels: Design

#110 #109 feat: 오픈그래프 설정
  public/Weeth_logo.svg
  public/Weeth_thumbnail.jpg
  public/index.html
  public/manifest.json
Labels: Feat

#111 #77 feat: member api 연결
  src/components/Member/Category.jsx
  src/components/Member/InfoComponent.jsx
  src/hooks/UserAPI.jsx
  src/hooks/UserContext.js
  src/pages/Edit.jsx
  src/pages/Member.jsx
  src/pages/MyPage.jsx
Labels: Feat

#114 [hotfix] 메타태그 누락 수정
  public/index.html
  src/hooks/UserAPI.jsx
Labels: Fix

#116 #112 feat: 캘린더 api 연결
  .eslintignore
  src/App.js
  src/components/BoardTitle.jsx
  src/components/Calendar/MonthCalendar.jsx
  src/components/Calendar/MonthlyEvent.jsx
  src/components/Calendar/YearCalendar.jsx
  src/hooks/EventAPI.jsx
  src/hooks/EventContext.js
  src/pages/Calendar.jsx
  src/pages/Edit.jsx
  src/pages/EventDetails.jsx
  src/pages/MyPage.jsx
Labels: Feat

#120 #105 feat: 출석 api 연결
  src/components/Attendance/AttendCheckMain.jsx
  src/components/Attendance/AttendMain.jsx
  src/components/Attendance/Modal/ModalPenalty.jsx
  src/hooks/PenaltyContext.js
  src/pages/AttendCheck.jsx
  src/pages/Attendance.jsx
Labels: Fix, Feat

#123 #121 feat: 출석체크 api 연결
  src/components/Attendance/AttendMain.jsx
  src/components/Attendance/Modal/ModalAttend.jsx
  src/components/Button/Button.jsx
  src/hooks/AttendContext.js
  src/hooks/PenaltyContext.js
  src/pages/Attendance.jsx
  src/pages/Login.jsx
Labels: Fix, Feat

#125 #119 feat: 유저 api 연결
  .eslintignore
  src/components/DropdownMenu.jsx
  src/components/MyPage/InfoInput.jsx
  src/components/MyPage/MyPageHeader.jsx
  src/hooks/UserContext.js
  src/pages/Edit.jsx
  src/pages/MyPage.jsx
  src/styles/theme.js
Labels: Feat

#130 #124 feat: 회비 api 연결
  src/App.js
  src/components/Receipt/ReceiptMain.jsx
  src/hooks/DuesContext.js
  src/pages/Dues.jsx
  src/pages/Login.jsx
  src/pages/Receipt.jsx
Labels: Fix, Feat

#131 #127 feat: 로그인 페이지 API 연결 /기능 구현하기(최종)
  .eslintignore
  src/hooks/Utils.js
  src/pages/Login.jsx
Labels: Feat

#133 #132 fix: 회비 수입 수정
  src/components/Dues/DueCategory.jsx
  src/components/Dues/DuesInfo.jsx
  src/components/Receipt/ReceiptMain.jsx
  src/hooks/DuesContext.js
  src/pages/Dues.jsx
Labels: Fix

#137 #136 fix: 자잘한 오류 수정 및 회비 페이지 total 돈 제거
  src/components/Attendance/AttendMain.jsx
  src/components/Button/Button.jsx
  src/pages/Dues.jsx
  src/pages/Landing.jsx
Labels: Fix

#138 #128 feat: 어드민 api 연결
  src/App.js
  src/assets/images/ic_plus.svg
  src/components/BoardTitle.jsx
  src/components/Calendar/CalendarHeader.jsx
  src/components/Calendar/DateInput.jsx
  src/components/Calendar/ModalMonthContent.jsx
  src/components/EditDelModal.jsx
  src/components/Header/Header.jsx
  src/components/MyPage/InfoInput.jsx
  src/pages/CreateEvent.jsx
  src/pages/Edit.jsx
  src/pages/EditEvent.jsx
  src/pages/EventDetails.jsx
Labels: Feat

#140 #134 feat: 게시물 생성 api 연결, 기능 구현
  .eslintignore
  src/components/Board/FileAttachMenu.jsx
  src/components/Board/StudyList.jsx
  src/pages/BoardPosting.jsx
Labels: Feat

#141 #139 feat: 탈퇴하기 버튼으로 수정 및 로그아웃 버튼 추가
  src/assets/images/ic_logout_gray.svg
  src/assets/images/ic_logout_white.svg
  src/pages/MyPage.jsx
Labels: Feat

#144 #143 feat: 일정 수정 api
  src/components/BoardTitle.jsx
  src/pages/EditEvent.jsx
  src/pages/EventDetails.jsx
Labels: Feat

#146 #135 feat: 회원가입 api 연결
  src/components/SignupDropDown.jsx
  src/pages/Profile.jsx
  src/pages/Signup.jsx
Labels: Fix, Feat

#148 #142 feat: 특정 게시물 삭제 api 연결
  src/components/Board/FileAttachMenu.jsx
  src/components/Board/NoticeHeader.jsx
  src/components/Board/NoticeMiddle.jsx
  src/pages/Board.jsx
  src/pages/BoardDetail.jsx
  src/pages/BoardPosting.jsx
Labels: Feat

#150 #147 design: 홈 이미지 추가
  .eslintignore
  src/assets/images/ic_commitato.svg
  src/assets/images/ic_discord.svg
  src/assets/images/ic_filling.svg
  src/assets/images/ic_github.svg
  src/assets/images/ic_gradu.svg
  src/assets/images/ic_insta.svg
  src/assets/images/ic_leets.svg
  src/assets/images/ic_moodmate.svg
  src/components/LogoutButton.jsx
  src/components/SignupDropDown.jsx
  src/components/home/HomeFooter.jsx
  src/pages/Home.jsx
  src/pages/Profile.jsx
  src/utils/handleLogout.js
Labels: Fix, Feat, Design

#155 #151 fix: 로그인 api 연결시 로컬에 토큰 저장
  src/components/home/HomeMain.css
  src/hooks/Utils.js
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/utils/setupInterceptors .js
Labels: Fix

#152 #145 feat: 캘린더 모달 수정
  src/components/Calendar/DateInput.jsx
  src/components/Calendar/ModalMonthContent.jsx
  src/components/Calendar/MonthlyEvent.jsx
  src/components/Calendar/YearCalendar.jsx
  src/components/Member/MemberName.jsx
  src/components/MyPage/InfoInput.jsx
  src/hooks/EventAPI.jsx
  src/hooks/EventContext.js
  src/pages/Calendar.jsx
  src/pages/Login.jsx
Labels: Fix

#160 #159 hotfix: 어드민 생성 수정 오류 고침
  src/components/Calendar/MonthlyEvent.jsx
  src/pages/CreateEvent.jsx
  src/pages/EditEvent.jsx
Labels: Fix

#158 #156 fix: 로컬 토큰으로 수정
  src/components/Attendance/AttendCheckMain.jsx
  src/components/Attendance/Modal/ModalAttend.jsx
  src/components/Attendance/Modal/ModalPenalty.jsx
  src/components/Calendar/MonthlyEvent.jsx
  src/hooks/AttendContext.js
  src/hooks/DuesContext.js
  src/hooks/PenaltyContext.js
  src/hooks/UserAPI.jsx
  src/hooks/Utils.js
  src/pages/Login.jsx
  src/pages/Profile.jsx
  src/pages/Signup.jsx
  src/utils/setupInterceptors .js
Labels: Fix

#164 #154 feat: 예외처리
  src/App.js
  src/components/Calendar/DateInput.jsx
  src/components/Calendar/ModalMonthContent.jsx
  src/components/Calendar/MonthCalendar.jsx
  src/components/MyPage/InfoInput.jsx
  src/hooks/EventAPI.jsx
  src/hooks/EventInfoAPI.jsx
  src/hooks/EventInfoContext.js
  src/hooks/UserAPI.jsx
  src/pages/CreateEvent.jsx
  src/pages/Edit.jsx
  src/pages/EditEvent.jsx
  src/pages/EventDetails.jsx
  src/pages/Member.jsx
  src/pages/MyPage.jsx
Labels: Feat

#166 [hotfix] 태그 오류 수정
  src/App.js
Labels: Fix

#167 #161 fix: 홈 api 및 자잘한 에러 수정
  src/assets/images/ic_logo.svg
  src/assets/images/ic_name_logo.svg
  src/components/Dues/DuesInfo.jsx
  src/components/home/HomeFooter.jsx
  src/hooks/AttendContext.js
  src/hooks/BoardAPI.jsx
  src/hooks/DuesAPI.jsx
  src/hooks/DuesContext.js
  src/hooks/Utils.js
  src/pages/Dues.jsx
  src/pages/Home.jsx
  src/pages/Landing.jsx
  src/pages/Login.jsx
  src/utils/handleLogout.js
Labels: Feat
