Repository Leets-Makers/Weeth-FE, pull requests merged in 2024-12, with the labels that each got.

#284 #283 chore: admin 폴더 기초 세팅
  src/App.jsx
  src/pages/admin/AdminAttendance.tsx
  src/pages/admin/AdminDues.tsx
  src/pages/admin/AdminMember.tsx
  src/pages/admin/AdminPenatly.tsx
  src/pages/admin/components/Button.tsx
  src/pages/admin/components/NavMenu.tsx
Labels: Feat

#286 #261 Feat: 게시글 목록 조회
  src/App.jsx
  src/api/BoardAPI.jsx
  src/api/BoardAPI.tsx
  src/api/BoardContext.jsx
  src/api/GetAllPostsContext.tsx
  src/api/NoticeAPI.jsx
  src/api/NoticeContext.jsx
  src/components/Board/CommentList.jsx
  src/components/Board/Info.tsx
  src/components/Board/PostList.tsx
  src/components/Board/PostListItem.tsx
  src/components/home/HomeMain.tsx
  src/components/mockData/mockBoard.jsx
  src/hooks/formatDate.tsx
  src/pages/NoticeBoard.tsx
  src/pages/StudyBoard.tsx
Labels: Fix, Feat, Design

#288 #287 Design: 게시판 스타일 분리
  src/api/BoardAPI.tsx
  src/components/Board/Comment.tsx
  src/components/Board/Info.tsx
  src/components/Board/PostDetailMain.tsx
  src/components/Board/PostFile.tsx
  src/components/Board/PostListItem.tsx
  src/components/Board/ReplyComment.tsx
  src/styles/board/Comment.styled.ts
  src/styles/board/PostDetail.styled.ts
  src/styles/board/PostFile.styled.ts
  src/styles/board/PostListItem.styled.ts
  src/styles/theme.ts
Labels: Fix, Design

#296 #295 fix: 컴포넌트 폴더 위치 변경
  src/components/Admin/Button.tsx
  src/components/Admin/NavMenu.tsx
  src/pages/admin/AdminMember.tsx
Labels: Fix

#294 #293 feat: 시즌별 로고 적용
  index.html
  package-lock.json
  package.json
  public/logo/Xmas.svg
  public/logo/original.svg
  src/assets/images/logo/logo_full_Xmas.svg
  src/assets/images/logo/logo_initial_Xmas.svg
  src/pages/Home.tsx
  src/pages/Landing.tsx
Labels: Feat

#299 #291 Feat: 무한스크롤 적용
  src/App.jsx
  src/api/BoardAPI.tsx
  src/api/GetAllPostsContext.tsx
  src/api/useDelComment.tsx
  src/api/useGetBoardInfo.tsx
  src/api/usePatchComment.tsx
  src/api/usePostComment.tsx
  src/components/Board/PostList.tsx
  src/pages/NoticeBoard.tsx
  src/pages/StudyBoard.tsx
Labels: Fix, Feat

#302 #297 feat: 어드민 출석 관리 UI 구현
  src/components/Admin/AttendDropdown.tsx
  src/components/Admin/Attendance.tsx
  src/components/Admin/Cardinal.tsx
  src/components/Admin/NavMenu.tsx
  src/pages/admin/AdminAttendance.tsx
Labels: Feat

#308 #279 feat: 멤버 api 연결
  src/App.jsx
  src/api/useGetUserDetail.tsx
  src/components/Member/Category.tsx
  src/components/Member/InfoComponent.tsx
  src/components/Member/MemberList.tsx
  src/components/Member/MemberName.tsx
  src/components/home/HomeMain.tsx
  src/pages/Home.tsx
  src/pages/MemberDetail.tsx
Labels: Feat

#307 #306 Feat: 게시물 상세 api 연결
  src/App.jsx
  src/api/useGetBoardDetail.tsx
  src/assets/images/ic_admin_cardinal.svg
  src/assets/images/ic_admin_check.svg
  src/components/Board/Comment.tsx
  src/components/Board/PostCommentList.tsx
  src/components/Board/PostDetailMain.tsx
  src/components/Board/ReplyComment.tsx
  src/pages/NoticePostDetail.tsx
  src/pages/StudyPostDetail.tsx
  src/styles/board/PostDetail.styled.ts
Labels: Fix, Feat

#311 #300 feat:어드민 멤버 관리 UI 구현
  src/assets/images/ic_admin_attendance.svg
  src/assets/images/ic_admin_checkbox.svg
  src/assets/images/ic_admin_due.svg
  src/assets/images/ic_admin_manual.svg
  src/assets/images/ic_admin_meatball.svg
  src/assets/images/ic_admin_penalty.svg
  src/assets/images/ic_admin_service_transfer.svg
  src/assets/images/ic_admin_uncheckbox.svg
  src/assets/images/ic_admin_user.svg
  src/components/Admin/CardinalInfo.tsx
  src/components/Admin/MemberListTable.tsx
  src/components/Admin/MemberListTableHeader.tsx
  src/components/Admin/MemberListTableRow.tsx
  src/components/Admin/NavHeader.tsx
  src/components/Admin/NavMenu.tsx
  src/components/Admin/NavMenuItem.tsx
  src/components/Admin/NavMenuList.tsx
  src/components/Admin/SearchBar.tsx
  src/components/Admin/StatusIndicator.tsx
  src/components/Admin/TopBar.tsx
  src/pages/admin/AdminMember.tsx
  src/types/declarations.d.ts
Labels: Feat, Design

#314 #312 feat: 불필요한 코드 제거
  src/App.jsx
  src/api/UserAPI.tsx
  src/api/UserContext.tsx
  src/components/Board/AttachButton.jsx
  src/components/Board/BoardComment.jsx
  src/components/Board/BoardComponent.jsx
  src/components/Board/CommentList.jsx
  src/components/Board/FileAttachMenu.jsx
  src/components/Board/NoticeComponent.jsx
  src/components/Board/NoticeList.jsx
  src/components/Board/NoticeMiddle.jsx
  src/components/Board/PostingHeader.jsx
  src/components/Board/StudyComponent.jsx
  src/components/Board/StudyList.jsx
  src/components/Board/Typing.jsx
  src/components/Header/Header.tsx
  src/components/MyPage/MyInfo.tsx
  src/pages/Board.jsx
  src/pages/Edit.tsx
  src/pages/MyPage.tsx
  src/pages/NoticeDetail.jsx
  src/pages/StudyDetail.jsx
  src/types/declarations.d.ts
Labels: Feat

#315 #310 feat: 출석 기수 컴포넌트 UI
  src/assets/images/ic_admin_absence.svg
  src/assets/images/ic_admin_check.svg
  src/components/Admin/AttendDropdown.tsx
  src/components/Admin/Cardinal.tsx
  src/components/Admin/NavMenu.tsx
  src/pages/admin/AdminAttendance.tsx
  src/pages/admin/AdminMember.tsx
  src/styles/admin/AdminLayout.styled.ts
  src/styles/admin/AttendDropdown.styled.ts
Labels: Feat, Design
