Repository Leets-Makers/Weeth-FE, pull requests merged in 2024-08, with the labels that each got.

#171 #169 hotfix: 수정페이지 원상복구
  src/components/DropdownMenu.jsx
  src/components/MyPage/InfoInput.jsx
  src/pages/Edit.jsx
  src/pages/MyPage.jsx
Labels: Fix

#173 #172 feat: 일정 관련 수정
  src/components/Calendar/MonthCalendar.jsx
  src/components/Calendar/MonthlyEvent.jsx
  src/components/Calendar/YearCalendar.jsx
  src/hooks/Utils.js
  src/pages/Calendar.jsx
  src/pages/CreateEvent.jsx
  src/pages/EventDetails.jsx
Labels: Feat

#174 #170 fix: 글쓰기 페이지 X버튼 클릭 시 사진 삭제 기능 구현
  .eslintignore
  src/components/Board/AttachButton.jsx
  src/components/Board/FileAttachMenu.jsx
  src/pages/BoardDetail.jsx
  src/pages/BoardPosting.jsx
Labels: Fix

#180 #175 feat: 바뀐 api에 따른 게시물 생성,조회,삭제,수정 기능 수정하기
  .eslintignore
  src/App.js
  src/components/Board/BoardComponent.jsx
  src/components/Board/NoticeList.jsx
  src/components/Board/StudyList.jsx
  src/hooks/BoardAPI.jsx
  src/pages/BoardDetail.jsx
  src/pages/BoardPosting.jsx
Labels: Fix, Feat

#182 #179 fix: 출석 에러 수정
  src/App.js
  src/components/Attendance/AttendCheckMain.jsx
  src/components/Attendance/AttendMain.jsx
  src/components/Attendance/Modal/ModalAttend.jsx
  src/components/Attendance/Modal/ModalPenalty.jsx
  src/hooks/AttendAPI.jsx
  src/hooks/AttendCheckAPI.jsx
  src/hooks/AttendContext.js
  src/hooks/PenaltyAPI.jsx
  src/hooks/PenaltyContext.js
  src/pages/AttendCheck.jsx
  src/pages/Login.jsx
  src/router/PrivateRouter.jsx
Labels: Fix, Feat

#186 #183 fix: 출석 체크 api 수정
  src/App.js
  src/components/Attendance/AttendCheckMain.jsx
  src/components/Attendance/AttendMain.jsx
  src/components/Attendance/Modal/ModalAttend.jsx
  src/components/Dues/DuesInfo.jsx
  src/hooks/AttendAPI.jsx
  src/pages/Dues.jsx
Labels: Fix

#190 #185 refactor: 일정 수정생성 통합
  src/App.js
  src/components/BoardTitle.jsx
  src/components/Calendar/DatePicker.jsx
  src/hooks/EventAdminAPI.jsx
  src/hooks/EventInfoAPI.jsx
  src/pages/CreateEvent.jsx
  src/pages/EditEvent.jsx
  src/pages/EventAdmin.jsx
  src/pages/EventDetails.jsx
Labels: Feat, Refactor

#192 #187 feat: 이메일 유효성 검사
  src/components/Attendance/AttendHeader.jsx
  src/components/Attendance/Modal/ModalAttend.jsx
  src/components/Attendance/Modal/ModalPenalty.jsx
  src/components/Signup/BackButton.jsx
  src/components/Signup/SignupDropDown.jsx
  src/components/Signup/SignupHeader.jsx
  src/components/Signup/SignupMemInput.jsx
  src/pages/Dues.jsx
  src/pages/Profile.jsx
  src/pages/Signup.jsx
Labels: Fix

#194 #193 fix: 회비 수정사항 적용
  src/components/Dues/DuesTitle.jsx
  src/components/Receipt/ReceiptMain.jsx
  src/hooks/DuesAPI.jsx
  src/hooks/DuesContext.js
  src/pages/Dues.jsx
Labels: Fix, Design

#195 #191 fix: 피드백 및 수정사항
  public/index.html
  src/App.js
  src/components/BoardTitle.jsx
  src/components/EditDelModal.jsx
  src/pages/EventDetails.jsx
  src/pages/Member.jsx
  src/router/ScrollToTop.jsx
Labels: Fix, Design

#198 #196 fix: 멤버 카테고리 및 뒤로가기 수정
  src/components/Calendar/MonthCalendar.jsx
  src/components/DropdownMenu.jsx
  src/components/Member/Category.jsx
  src/components/MyPage/InfoInput.jsx
  src/pages/AttendCheck.jsx
  src/pages/Attendance.jsx
  src/pages/Calendar.jsx
  src/pages/Dues.jsx
  src/pages/Edit.jsx
  src/pages/EventAdmin.jsx
  src/pages/EventDetails.jsx
  src/pages/Home.jsx
  src/pages/Landing.jsx
  src/pages/Login.jsx
  src/pages/Member.jsx
  src/pages/MemberDetail.jsx
  src/pages/MyPage.jsx
  src/pages/Profile.jsx
  src/pages/Receipt.jsx
  src/pages/Signup.jsx
  src/router/useCustomBack.jsx
Labels: Fix, Feat

#199 #197 fix: 패널티 에러 수정
  .eslintignore
  src/components/Attendance/AttendCheckMain.jsx
  src/components/Attendance/AttendMain.css
  src/components/Attendance/AttendMain.jsx
  src/components/Signup/SignupHeader.jsx
  src/components/Signup/SignupMemInput.jsx
  src/hooks/PenaltyAPI.jsx
  src/hooks/PenaltyContext.js
  src/pages/Dues.jsx
  src/pages/Login.jsx
  src/pages/Profile.jsx
  src/pages/Signup.jsx
Labels: Fix, Design

#201 #200 fix: 날짜 입력 제한 수정
  src/components/Calendar/CalendarHeader.jsx
  src/components/Calendar/DateInput.jsx
  src/components/Calendar/MonthCalendar.jsx
  src/components/Calendar/YearCalendar.jsx
  src/components/Header/Header.jsx
  src/components/Member/Category.jsx
  src/components/MyPage/MyPageHeader.jsx
  src/index.css
  src/pages/Member.jsx
Labels: Fix

#202 Feat#189/오류 수정 및 공지사항 api 연결하기
  src/App.js
  src/components/Board/AttachButton.jsx
  src/components/Board/BoardComment.jsx
  src/components/Board/BoardComponent.jsx
  src/components/Board/CommentList.jsx
  src/components/Board/FileAttachMenu.jsx
  src/components/Board/NoticeHeader.jsx
  src/components/Board/NoticeList.jsx
  src/components/Board/NoticeMiddle.jsx
  src/components/Board/StudyList.jsx
  src/components/Board/Typing.jsx
  src/hooks/BoardContext.js
  src/pages/Board.jsx
  src/pages/NoticeDetail.jsx
  src/pages/NoticePosting.jsx
  src/pages/StudyDetail.jsx
  src/pages/StudyPosting.jsx
Labels: Fix, Feat

#204 Feat#203/입력창 고정하기 게시글 더 불러오기 버튼 수정
  src/components/Board/BoardComment.jsx
  src/components/Board/CommentList.jsx
  src/components/Board/FileAttachMenu.jsx
  src/components/Board/NoticeHeader.jsx
  src/components/Board/NoticeList.jsx
  src/pages/NoticeDetail.jsx
  src/pages/StudyDetail.jsx
Labels: Fix, Feat

#207 #206 fix: 출석 상태 변경
  src/components/Attendance/AttendCheckMain.jsx
  src/components/Attendance/AttendMain.jsx
  src/components/Receipt/ReceiptInfo.jsx
  src/components/home/HomeMain.jsx
  src/hooks/UserAPI.jsx
  src/pages/Login.jsx
Labels: Fix

#209 #208 feat: 댓글 대댓글 기능 수정마무리
  src/components/Board/BoardComment.jsx
  src/components/Board/CommentList.jsx
Labels: Fix, Feat

#211 #210 feat: 모바일에서의 변경 사항 적용 및 백 엔터 치환
  src/App.js
  src/assets/images/ic_moreButton.svg
  src/components/Board/BoardComment.jsx
  src/components/Board/BoardComponent.jsx
  src/components/Board/CommentList.jsx
  src/components/Board/NoticeList.jsx
  src/components/Board/StudyList.jsx
  src/components/Board/Typing.jsx
  src/pages/BoardEdit.jsx
  src/pages/NoticeDetail.jsx
  src/pages/NoticePosting.jsx
  src/pages/StudyDetail.jsx
  src/pages/StudyPosting.jsx
Labels: Fix, Feat, Design

#217 #214 fix: 최종 수정사항 정리하기
  src/components/Board/NoticeList.jsx
  src/components/Board/StudyList.jsx
  src/pages/Home.jsx
Labels: Fix, Feat

#218 #216 fix: util 수정
  src/App.js
  src/components/Attendance/AttendCheckMain.jsx
  src/components/Attendance/AttendMain.jsx
  src/components/home/HomeMain.jsx
  src/hooks/DuesAPI.jsx
  src/hooks/UserAPI.jsx
  src/hooks/Utils.js
  src/pages/Home.jsx
  src/pages/Login.jsx
Labels: Fix

#220 #219 feat: 자동 로그인 추가
  src/App.js
  src/components/Board/AttachButton.jsx
  src/components/Board/BoardComment.jsx
  src/components/Board/CommentList.jsx
  src/components/Board/Typing.jsx
  src/components/Button/MiddleButton.jsx
  src/components/Button/SmallButton.jsx
  src/components/Caption.jsx
  src/components/Receipt/ReceiptMain.jsx
  src/components/home/HomeMain.jsx
  src/hooks/MonthlyScheduleAPI.jsx
  src/hooks/YearlyScheduleAPI.jsx
  src/pages/Landing.jsx
  src/pages/NoticeDetail.jsx
  src/pages/NoticePosting.jsx
  src/pages/Signup.jsx
  src/pages/StudyDetail.jsx
  src/pages/StudyPosting.jsx
Labels: Fix

#222 #215 fix: QA 수정
  .eslintignore
  src/components/BoardTitle.jsx
  src/components/Calendar/CalendarHeader.jsx
  src/components/Calendar/DateInput.jsx
  src/components/Calendar/ModalMonthContent.jsx
  src/components/Calendar/MonthCalendar.jsx
  src/components/Calendar/MonthlyEvent.jsx
  src/components/Calendar/ToggleButton.jsx
  src/components/Calendar/YearCalendar.jsx
  src/components/Member/Category.jsx
  src/components/Member/MemberHeader.jsx
  src/components/Member/MemberName.jsx
  src/hooks/MonthlyScheduleAPI.jsx
  src/hooks/YearlyScheduleAPI.jsx
  src/pages/Calendar.jsx
  src/pages/Member.jsx
Labels: Fix

#225 #224 fix: qa 수정사항 적용
  src/hooks/LoginAPI.jsx
  src/pages/AttendCheck.jsx
  src/pages/Attendance.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: Fix

#226 #221 fix: 게시판 수정 사항 수정하기
  src/components/Board/BoardComponent.jsx
  src/components/Board/CommentList.jsx
  src/components/Board/NoticeList.jsx
  src/components/Board/StudyList.jsx
  src/components/Board/Typing.jsx
  src/pages/NoticeDetail.jsx
  src/pages/StudyDetail.jsx
Labels: Fix, Feat, Design

#228 #227 fix: 최종 수정사항 수정하기
  src/components/Board/AttachButton.jsx
  src/components/Board/BoardComponent.jsx
  src/pages/NoticeDetail.jsx
  src/pages/NoticePosting.jsx
  src/pages/StudyDetail.jsx
  src/pages/StudyPosting.jsx
Labels: Fix

#229 #223 fix: 어드민 일정 오류 수정
  src/App.js
  src/components/Calendar/DateInput.jsx
  src/components/Calendar/DatePicker.jsx
  src/components/Calendar/EventDetailTitle.jsx
  src/components/Calendar/MonthCalendar.jsx
  src/components/Member/MemberName.jsx
  src/components/MyPage/InfoInput.jsx
  src/components/home/HomeFooter.jsx
  src/hooks/EventInfoAPI.jsx
  src/hooks/MonthlyScheduleAPI.jsx
  src/pages/Edit.jsx
  src/pages/EventAdmin.jsx
  src/pages/EventDetails.jsx
  src/pages/Member.jsx
  src/pages/Signup.jsx
Labels: Fix

#232 #230 fix: 게시물 첨부 버튼 수정하기
  src/components/Board/AttachButton.jsx
  src/components/Board/FileAttachMenu.jsx
  src/pages/NoticeDetail.jsx
  src/pages/NoticePosting.jsx
  src/pages/StudyDetail.jsx
  src/pages/StudyPosting.jsx
Labels: Fix

#233 #231 fix: 엔터로 페이지 넘어가기
  src/components/Signup/SignupTextComponent.jsx
  src/pages/Login.jsx
  src/pages/Profile.jsx
  src/pages/Signup.jsx
Labels: Fix
