Repository Leets-Makers/Weeth-FE, pull requests merged in 2025-02, with the labels that each got.

#344 #340 feat: 일정 상세 UI 수정
  src/App.jsx
  src/api/EventAdminAPI.tsx
  src/assets/images/ic_default_dropdown.svg
  src/assets/images/ic_opened_dropdown.svg
  src/components/Calendar/CalendarToggle.tsx
  src/components/Calendar/ToggleButton.tsx
  src/components/Event/CardinalLabel.tsx
  src/components/Event/EventContent.tsx
  src/components/Event/EventEditor.tsx
  src/components/Event/EventInput.tsx
  src/components/Event/EventTitle.tsx
  src/components/Event/Tag.tsx
  src/components/Header/Header.tsx
  src/components/common/CardinalDropdown.tsx
  src/components/common/Modal.tsx
  src/components/common/ToggleButton.tsx
  src/hooks/toTwoDigits.tsx
  src/pages/Calendar.tsx
  src/pages/EventDetail.tsx
  src/pages/EventPost.tsx
  src/styles/calendar/EventDetailTitle.styled.ts
  src/styles/calendar/YearCalendar.styled.ts
  src/styles/event/EventContent.styled.ts
  src/styles/event/EventDetail.styled.ts
  src/styles/event/EventEditor.styled.ts
Labels: Feat, Refactor, Design

#349 #348 feat: 마이페이지 디자인 수정
  src/api/usePatchMyInfo.tsx
  src/assets/images/ic_fullscreen.svg
  src/assets/images/ic_smallscreen.svg
  src/components/Button/DropdownMenu.tsx
  src/components/Event/EventContent.tsx
  src/components/Event/EventEditor.tsx
  src/components/Header/EditButton.tsx
  src/components/Header/Header.tsx
  src/components/Member/InfoComponent.tsx
  src/components/Member/MemberList.tsx
  src/components/MyPage/InfoInput.tsx
  src/components/MyPage/InfoItem.tsx
  src/components/MyPage/MyInfo.tsx
  src/components/common/CardinalTag.tsx
  src/components/common/MenuModal.tsx
  src/components/common/Modal.tsx
  src/pages/Edit.tsx
  src/pages/MyPage.tsx
  src/styles/event/EventContent.styled.ts
  src/styles/member/MemberList.styled.ts
  src/styles/mypage/InfoInput.styled.ts
  src/styles/mypage/Mypage.styled.ts
Labels: Feat, Refactor, Design

#355 #345 Feat: 사용자 어드민 api 연결
  package-lock.json
  src/api/admin/member/deleteUser.tsx
  src/api/admin/member/getAdminUser.tsx
  src/api/admin/member/patchUserManagement.tsx
  src/components/Admin/ButtonGroup.tsx
  src/components/Admin/MemberListTable.tsx
  src/components/Admin/MemberListTableHeader.tsx
  src/components/Admin/MemberListTableRow.tsx
  src/components/Admin/Modal/MemberDetailModal.tsx
  src/components/Admin/NavHeader.tsx
  src/components/Admin/NavMenu.tsx
  src/components/Admin/NavMenuItem.tsx
  src/components/Admin/NavMenuList.tsx
  src/components/Admin/PenaltyListTable.tsx
  src/components/Admin/SelectedTopBar.tsx
  src/components/Admin/SortButton.tsx
  src/components/Admin/context/MemberContext.tsx
  src/hooks/useAdminActions.ts
  src/pages/admin/AdminMember.tsx
  src/styles/admin/penalty/Penalty.styled.ts
Labels: Feat, Refactor

#359 #354 Feat: 어드민 출석 관리 api 연결
  src/api/admin/attendance/fetchAttendancesByCardinal.ts
  src/api/admin/attendance/getAttendance.ts
  src/api/admin/attendance/updateAttendanceStatus.ts
  src/api/admin/dues/getAccount.ts
  src/api/admin/dues/postRegisterDues.ts
  src/components/Admin/AttendDropdown.tsx
  src/components/Admin/Attendance.tsx
  src/components/Admin/Cardinal.tsx
  src/components/Admin/CardinalSearchBar.tsx
  src/components/Admin/CardinalWrapper.tsx
  src/components/Admin/DuesRegisterAdd.tsx
  src/components/Admin/DuesRegisterDropDown.tsx
  src/components/Admin/ExpenditureRecord.tsx
  src/components/Admin/Modal/DuesModifyModal.tsx
  src/components/Admin/SearchInput.tsx
  src/components/Admin/TotalDues.tsx
  src/pages/admin/AdminAttendance.tsx
  src/styles/admin/AttendDropdown.styled.ts
  src/styles/admin/Attendance.styled.ts
Labels: Fix, Feat

#304 #304 feat: 로그인 로직 변경
  .eslintrc.json
  jest.config.cjs
  package-lock.json
  package.json
  src/App.jsx
  src/api/EventAdminAPI.tsx
  src/api/UserAPI.tsx
  src/api/api.test.ts
  src/api/api.ts
  src/api/deleteUser.tsx
  src/api/getEventInfo.tsx
  src/api/useGetAllUsers.tsx
  src/api/useGetAttend.tsx
  src/api/useGetAttendCheck.tsx
  src/api/useGetBoardInfo.tsx
  src/api/useGetDuesInfo.tsx
  src/api/useGetMonthSchedule.tsx
  src/api/useGetPenalty.tsx
  src/api/useGetUserInfo.tsx
  src/api/useGetYearlySchedule.tsx
  src/assets/images/ic_KAKAO_symbol.svg
  src/assets/images/ic_account_arrow.svg
  src/assets/images/ic_register_success.svg
  src/assets/images/ic_register_weeth.svg
  src/assets/images/ic_waiting_approval.svg
  src/components/AccountCheck/AccountButton.tsx
  src/components/AccountCheck/Title.tsx
  src/components/Attendance/Modal/ModalAttend.tsx
  src/components/Board/BoardComment.jsx
  src/components/Board/CommentList.jsx
  src/components/Board/NoticeList.jsx
  src/components/Board/StudyList.jsx
  src/components/Board/Typing.jsx
  src/components/Signup/SignupMemInput.tsx
  src/pages/AccountCheck.tsx
  src/pages/Edit.tsx
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/NoticeDetail.jsx
  src/pages/Profile.tsx
  src/pages/Redirect.tsx
  src/pages/RegistrationSuccess.tsx
  src/pages/StudyDetail.jsx
  src/pages/WaitingApproval.tsx
  src/styles/theme.ts
  tsconfig.jest.json
  tsconfig.json
  vite.config.js
Labels: Feat

#363 #358 Refactor: 어드민 회비 api 연결
  src/api/admin/attendance/fetchAttendancesByCardinal.ts
  src/components/Admin/AttendDropdown.tsx
  src/components/Admin/Attendance.tsx
  src/components/Admin/Cardinal.tsx
  src/components/Admin/DuesRegisterAdd.tsx
  src/components/Admin/ExpenditureRecord.tsx
  src/components/Admin/Modal/DuesModifyModal.tsx
  src/components/Admin/Modal/ReceiptModal.tsx
  src/components/Admin/TotalDues.tsx
  src/constants/admin/duesRegisterAddConstants.ts
  src/hooks/admin/handleFileChange.tsx
  src/hooks/admin/useUploadFile.ts
  src/pages/admin/AdminDues.tsx
  src/styles/admin/AttendDropdown.styled.ts
  src/styles/admin/DuesRegisterAdd.styled.ts
Labels: Fix, Refactor

#361 #281 feat: 어드민 체크 분리
  src/App.jsx
  src/api/useGetDuesInfo.tsx
  src/api/useGetGlobaluserInfo.tsx
  src/components/Dues/DuesTitle.tsx
  src/components/Event/EventEditor.tsx
  src/components/Receipt/ReceiptMain.tsx
  src/components/common/AdminOnly.tsx
  src/components/home/HomeMain.tsx
  src/hooks/useGetUserName.tsx
  src/pages/Dues.tsx
  src/pages/EventDetail.tsx
  src/pages/EventPost.tsx
  src/pages/admin/AdminAttendance.tsx
  src/pages/admin/AdminDues.tsx
  src/pages/admin/AdminMember.tsx
  src/pages/admin/AdminPenalty.tsx
Labels: Feat

#360 #350 feat: 게시글 생성하기 수정
  package-lock.json
  package.json
  src/App.jsx
  src/api/EventAdminAPI.tsx
  src/api/editBoard.tsx
  src/api/editNotice.tsx
  src/api/postBoard.tsx
  src/api/postNotice.tsx
  src/api/uploadFiles.tsx
  src/api/useGetBoardDetail.tsx
  src/api/useGetFileUrl.tsx
  src/components/Board/FileUploader.tsx
  src/components/Board/PostEditor.tsx
  src/components/Button/DropdownMenu.tsx
  src/components/Event/CardinalLabel.tsx
  src/components/Event/EventContent.tsx
  src/components/Event/EventEditor.tsx
  src/components/Event/EventTitle.tsx
  src/components/Event/Tag.tsx
  src/components/Modal/EditDelModal.tsx
  src/components/MyPage/InfoInput.tsx
  src/components/common/CardinalDropdown.tsx
  src/components/common/MenuModal.tsx
  src/components/common/ToggleButton.tsx
  src/pages/Board.tsx
  src/pages/BoardPost.tsx
  src/pages/BoardPostDetail.tsx
  src/pages/EventDetail.tsx
  src/pages/MyPage.tsx
  src/pages/Notice.tsx
  src/pages/NoticePostDetail.tsx
  src/styles/board/BoardPost.styled.ts
  src/styles/calendar/EventDetailTitle.styled.ts
  src/styles/calendar/MonthCalendar.styled.ts
  src/styles/event/DatePicker.css
  src/styles/event/EventEditor.styled.ts
Labels: Feat, Refactor

#365 #336 Feat: 홈 공지사항 추가
  package-lock.json
  src/api/useGetBoardInfo.tsx
  src/api/useGetUserInfo.tsx
  src/assets/images/ic_char_BE_hover.svg
  src/assets/images/ic_char_DE_hover.svg
  src/assets/images/ic_char_FE_hover.svg
  src/components/Board/BoardComment.jsx
  src/components/Board/CommentList.jsx
  src/components/Board/NoticeList.jsx
  src/components/Board/StudyList.jsx
  src/components/Board/Typing.jsx
  src/components/home/HomeFooter.tsx
  src/components/home/HomeInfo.tsx
  src/components/home/HomeMain.tsx
  src/components/home/HomeNotice.tsx
  src/index.css
  src/pages/Board.tsx
  src/pages/Home.tsx
  src/pages/Notice.tsx
  src/styles/home/HomeInfo.styled.ts
  src/styles/home/HomeMain.styled.ts
  vite.config.js
Labels: Fix, Feat, Refactor, Design

#371 #356 Feat: 어드민 페널티 api 연결
  src/api/admin/member/deleteUser.tsx
  src/api/admin/member/patchUserManagement.tsx
  src/api/admin/penalty/getPenalty.ts
  src/api/admin/penalty/modifyPenalty.ts
  src/assets/images/ic_admin_attendance.svg
  src/components/Admin/CardinalInfo.tsx
  src/components/Admin/CardinalSearchBar.tsx
  src/components/Admin/CardinalWrapper.tsx
  src/components/Admin/MemberListTable.tsx
  src/components/Admin/MemberListTableHeader.tsx
  src/components/Admin/MemberListTableRow.tsx
  src/components/Admin/Modal/CardinalEditModal.tsx
  src/components/Admin/Modal/CardinalModal.tsx
  src/components/Admin/Modal/CommonCardinalModal.tsx
  src/components/Admin/Modal/MemberDetailModal.tsx
  src/components/Admin/NavHeader.tsx
  src/components/Admin/NavMenu.tsx
  src/components/Admin/NavMenuItem.tsx
  src/components/Admin/NavMenuList.tsx
  src/components/Admin/PenaltyAdd.tsx
  src/components/Admin/PenaltyDetail.tsx
  src/components/Admin/PenaltyListTable.tsx
  src/components/Admin/SearchBar.tsx
  src/components/Admin/SelectedTopBar.tsx
  src/components/Admin/SortButton.tsx
  src/components/Admin/StatusList.tsx
  src/components/Admin/context/PenaltyReducer.ts
  src/hooks/admin/useAdminActions.ts
  src/pages/admin/AdminPenalty.tsx
  src/styles/admin/AdminLayout.styled.ts
  src/styles/admin/penalty/Penalty.styled.ts
  src/types/svg.d.ts
  vite.config.js
Labels: Fix, Feat, Design

#368 #338 Feat: 삭제 모달
  src/components/Board/Comment.tsx
  src/components/Board/ReplyComment.tsx
  src/components/Modal/DeleteModal.tsx
  src/components/common/Modal.tsx
  src/pages/BoardPostDetail.tsx
  src/pages/MyPage.tsx
  src/pages/NoticePostDetail.tsx
Labels: Fix, Feat, Design

#373 #353 Feat: 토스트 메세지
  package-lock.json
  package.json
  src/api/deletePost.tsx
  src/assets/images/ic_toast_warning.svg
  src/components/Attendance/AttendCheckMain.tsx
  src/components/Board/PostDetailMain.tsx
  src/components/common/ToastMessage.tsx
  src/pages/BoardPostDetail.tsx
  src/pages/MyPage.tsx
  src/pages/Notice.tsx
  src/pages/NoticeDetail.jsx
  src/pages/NoticePostDetail.tsx
  src/pages/StudyDetail.jsx
Labels: Fix, Feat

#369 #362 feat: 멤버 무한 스크롤 적용 및 검색 api 연결
  src/api/getSearchMember.tsx
  src/api/useGetAllUsers.tsx
  src/api/useGetBoardInfo.tsx
  src/api/useGetYearlySchedule.tsx
  src/components/Calendar/YearCalendar.tsx
  src/components/Calendar/YearlyCard.tsx
  src/components/Member/MemberList.tsx
  src/pages/Calendar.tsx
  src/pages/Edit.tsx
  src/pages/Member.tsx
  src/types/user.ts
Labels: Feat

#375 #370 feat: 날짜 선택 모달 구현
  package-lock.json
  package.json
  src/api/EventAdminAPI.tsx
  src/components/Event/DatePicker.tsx
  src/components/Event/EventContent.tsx
  src/components/Event/EventEditor.tsx
  src/components/Event/PickerModal.tsx
  src/components/Event/TimePicker.tsx
  src/pages/EventDetail.tsx
  src/styles/event/TimePicker.css
Labels: Feat, Design

#383 #378 Feat: 홈 파트 구분
  src/components/Attendance/Modal/ModalPenalty.tsx
  src/components/home/HomeInfo.tsx
  src/styles/board/Board.styled.ts
  src/styles/home/HomeInfo.styled.ts
Labels: Fix, Feat

#385 #380 feat: 공통모달 및 토스트 추가
  package-lock.json
  package.json
  src/App.jsx
  src/api/getEventInfo.tsx
  src/api/useGetAllUsers.tsx
  src/api/useGetCardinals.tsx
  src/api/useGetGlobaluserInfo.tsx
  src/api/useGetMonthSchedule.tsx
  src/api/useGetUserDetail.tsx
  src/api/useGetUserInfo.tsx
  src/api/useGetYearlySchedule.tsx
  src/api/usePatchMyInfo.tsx
  src/components/Board/PostDetailMain.tsx
  src/components/Calendar/DateInput.tsx
  src/components/Event/EventEditor.tsx
  src/components/Event/EventTitle.tsx
  src/components/common/Loading.tsx
  src/components/common/MenuModal.tsx
  src/components/common/WeethLoading.json
  src/pages/BoardPost.tsx
  src/pages/BoardPostDetail.tsx
  src/pages/Edit.tsx
  src/pages/MyPage.tsx
  src/pages/NoticePostDetail.tsx
  tsconfig.json
Labels: 🎨 Design

#387 #381 fix: 멤버 qa 수정
  src/App.jsx
  src/api/getEventInfo.tsx
  src/api/useGetAllUsers.tsx
  src/components/Event/EventTitle.tsx
  src/components/Member/MemberList.tsx
  src/components/common/CardinalDropdown.tsx
  src/components/common/MenuModal.tsx
  src/pages/BoardPostDetail.tsx
  src/pages/Member.tsx
  src/pages/MyPage.tsx
  src/pages/NoticePostDetail.tsx
Labels: 🐞 Fix, 🎨 Design
