Repository Leets-Makers/Weeth-FE, pull requests merged in 2025-01, with the labels that each got.

#322 #316 feat: 어드민 회비 관리 UI
  src/assets/images/ic_admin_receipt.svg
  src/components/Admin/Box.tsx
  src/components/Admin/Button.tsx
  src/components/Admin/Cardinal.tsx
  src/components/Admin/DuesInput.tsx
  src/components/Admin/DuesRegister.tsx
  src/components/Admin/DuesRegisterAdd.tsx
  src/components/Admin/DuesRegisterDropDown.tsx
  src/components/Admin/Expenditure.tsx
  src/components/Admin/ExpenditureRecord.tsx
  src/components/Admin/TotalDues.tsx
  src/index.jsx
  src/pages/admin/AdminAttendance.tsx
  src/pages/admin/AdminDues.tsx
  src/styles/admin/AdminLayout.styled.ts
  src/styles/admin/AttendDropdown.styled.ts
  src/styles/admin/DuesRegisterAdd.styled.ts
  src/styles/admin/DuesRegisterDropDown.styled.ts
  src/styles/admin/TotalDues.styled.ts
Labels: Feat, Design

#323 #321 feat: 게시판 목록 연결
  src/App.jsx
  src/components/Board/PostList.tsx
  src/components/Board/PostListItem.tsx
  src/pages/NoticeBoard.tsx
  src/pages/NoticePostDetail.tsx
  src/pages/StudyBoard.tsx
  src/pages/StudyPostDetail.tsx
Labels: Feat

#329 #327 feat: 멤버 상세 관리 모달 UI
  package-lock.json
  package.json
  src/assets/images/ic_admin_close.svg
  src/components/Admin/ButtonGroup.tsx
  src/components/Admin/Cardinal.tsx
  src/components/Admin/MemberListTableRow.tsx
  src/components/Admin/Modal/CommonModal.tsx
  src/components/Admin/Modal/MemberDetailModal.tsx
  src/components/Admin/Modal/MemberDetailsModal.tsx
  src/components/Admin/SelectedTopBar.tsx
  src/components/Admin/context/MemberContext.tsx
Labels: Feat, Design

#335 #325 Feat : 게시물 상세 기능
  src/api/deleteComment.tsx
  src/api/deletePost.tsx
  src/api/usePostComment.tsx
  src/components/Board/Comment.tsx
  src/components/Board/CommentInput.tsx
  src/components/Board/PostCommentList.tsx
  src/components/Board/PostDetailMain.tsx
  src/components/Board/ReplyComment.tsx
  src/pages/NoticePostDetail.tsx
  src/pages/StudyPostDetail.tsx
  src/styles/board/Comment.styled.ts
Labels: Fix, Feat, Design

#337 #328 Feat: 어드민 페널티 관리 페이지 UI
  src/App.jsx
  src/components/Admin/Button.tsx
  src/components/Admin/Cardinal.tsx
  src/components/Admin/CardinalInfo.tsx
  src/components/Admin/CardinalSearchBar.tsx
  src/components/Admin/MemberListTableRow.tsx
  src/components/Admin/Modal/AddCardinal.tsx
  src/components/Admin/PenaltyAdd.tsx
  src/components/Admin/PenaltyDetail.tsx
  src/components/Admin/PenaltyListTable.tsx
  src/components/Admin/SearchBar.tsx
  src/components/Admin/StatusIndicator.tsx
  src/components/Admin/context/MemberContext.tsx
  src/components/Admin/context/PenaltyReducer.ts
  src/pages/admin/AdminPenalty.tsx
  src/pages/admin/AdminPenatly.tsx
  src/styles/admin/penalty/Penalty.styled.ts
Labels: Feat, Design

#339 #334 feat: 캘린더 UI 변경
  src/assets/images/ic_leftArrow.svg
  src/assets/images/ic_rightArrow.svg
  src/components/Calendar/CalendarHeader.tsx
  src/components/Calendar/MonthCalendar.tsx
  src/components/Calendar/ScheduleItem.tsx
  src/components/Calendar/YearCalendar.tsx
  src/components/Calendar/YearlyCard.tsx
  src/components/Event/EventEditor.tsx
  src/components/Header/Header.tsx
  src/components/common/Line.tsx
  src/constants/dateConstants.ts
  src/hooks/TodayIncluded.tsx
  src/hooks/formatDate.tsx
  src/pages/AttendCheck.tsx
  src/pages/Attendance.tsx
  src/pages/BoardPost.tsx
  src/pages/Calendar.tsx
  src/pages/Dues.tsx
  src/pages/Edit.tsx
  src/pages/Member.tsx
  src/pages/MemberDetail.tsx
  src/pages/MyPage.tsx
  src/pages/NoticeBoard.tsx
  src/pages/NoticePostDetail.tsx
  src/pages/Profile.tsx
  src/pages/Receipt.tsx
  src/pages/Signup.tsx
  src/pages/StudyBoard.tsx
  src/pages/StudyPostDetail.tsx
  src/styles/calendar/Calendar.styled.ts
  src/styles/calendar/MonthCalendar.styled.ts
  src/styles/calendar/MonthlyEvent.styled.ts
  src/styles/calendar/YearCalendar.styled.ts
  src/styles/common/Header.styled.ts
  src/styles/theme.ts
Labels: Feat, Design

#343 #332 Feat:기수 관련 UI
  .vscode/settings.json
  src/components/Admin/AddCardinal.tsx
  src/components/Admin/CardinalInfo.tsx
  src/components/Admin/MemberListTable.tsx
  src/components/Admin/MemberListTableRow.tsx
  src/components/Admin/Modal/AddCardinal.tsx
  src/components/Admin/Modal/CardinalEditModal.tsx
  src/components/Admin/Modal/CardinalModal.tsx
  src/components/Admin/Modal/CommonCardinalModal.tsx
  src/components/Admin/Modal/CommonModal.tsx
  src/components/Admin/NavMenuItem.tsx
  src/components/Admin/PenaltyListTable.tsx
  src/components/Admin/SearchBar.tsx
  src/components/Admin/SelectedTopBar.tsx
  src/components/Admin/SortButton.tsx
  src/components/Admin/context/MemberContext.tsx
  src/styles/admin/AdminLayout.styled.ts
  src/styles/admin/cardinal/AdminCardinal.styled.ts
  src/styles/admin/penalty/Penalty.styled.ts
Labels: Feat, Design

#341 #333 feat: 회비 지출 기록 수정 UI
  src/api/admin/dues/account.ts
  src/components/Admin/CardinalWrapper.tsx
  src/components/Admin/DuesInput.tsx
  src/components/Admin/DuesModalButton.tsx
  src/components/Admin/ExpenditureRecord.tsx
  src/components/Admin/Modal/CommonModal.tsx
  src/components/Admin/Modal/DuesModifyModal.tsx
  src/components/Admin/Modal/MemberDetailModal.tsx
  src/components/Admin/TotalDues.tsx
  src/pages/admin/AdminDues.tsx
  src/styles/admin/DuesRegisterAdd.styled.ts
Labels: Feat, Design
