Repository Leets-Makers/Weeth-FE, pull requests merged in 2025-09, with the labels that each got.

#506 #505 Fix : 드롭다운 메뉴 기수 api 연결
  src/components/Button/DropdownMenu.tsx
  src/components/Signup/SignupDropDown.tsx
Labels: 🐞 Fix

#509 WTH-9-WEETH: 출석 어드민 헤더 관리자 페이지 추가
  src/components/Header/AdminButton.tsx
  src/components/Header/Header.tsx
  src/pages/attend/Attendance.tsx
Labels: 🐞 Fix, 🎨 Design

#513 WTH-16-WEETH: 릴리즈 후 qa 사항 반영
  package-lock.json
  src/components/Board/PartBoard.tsx
  src/components/Board/StudyBoardSearch.tsx
  src/components/Header/Header.tsx
  src/components/home/HomeFooter.tsx
Labels: 🎨 Design

#512 WTH-13-WEETH : 페널티 UI 수정
  src/components/Attendance/AttendMain.tsx
  src/components/Penalty/PenaltyItem.tsx
  src/styles/penalty/PenaltyItem.styled.ts
Labels: 🐞 Fix

#514 Release/v3.0.1
  package-lock.json
  src/components/Attendance/AttendMain.tsx
  src/components/Board/PartBoard.tsx
  src/components/Board/StudyBoardSearch.tsx
  src/components/Header/Header.tsx
  src/components/Penalty/PenaltyItem.tsx
  src/components/home/HomeFooter.tsx
  src/styles/penalty/PenaltyItem.styled.ts
Labels: 🌏 Deploy
