Repository Leets-Makers/Weeth-FE, pull requests merged in 2025-05, with the labels that each got.

#476 #474 Refactor: 유저 테스트 수정 반영
  index.html
  src/components/Admin/DirectCardinal.tsx
  src/components/Admin/DuesRegisterDropDown.tsx
  src/components/Dues/DuesInfo.tsx
  src/pages/admin/AdminAttendance.tsx
  src/pages/admin/AdminDues.tsx
  src/styles/admin/DuesRegisterAdd.styled.ts
  src/styles/admin/ExpenditureRecord.styled.ts
  src/styles/admin/TotalDues.styled.ts
  src/types/adminCardinal.d.ts
Labels: 🐞 Fix, 💻 Performance

#478 #475 Fix : 임원진 qa 반영
  src/components/Admin/NavMenuList.tsx
  src/components/Admin/SearchBar.tsx
  src/pages/admin/AdminMember.tsx
  src/styles/admin/AdminLayout.styled.ts
Labels: 💻 Performance, 🎨 Design

#480 #477 Refactor : 로그인/회원가입 유저 테스트 수정 반영
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/api/api.ts
  src/assets/images/ic_waiting_approval.svg
  src/components/Button/DropdownMenu.tsx
  src/components/Header/Header.tsx
  src/components/Header/LeftButton.tsx
  src/components/MyPage/InfoInput.tsx
  src/components/Signup/PositionSector.tsx
  src/components/common/CardinalDropdown.tsx
  src/components/common/PrivateRoute.tsx
  src/index.css
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/Profile.tsx
  src/pages/Redirect.tsx
  src/pages/RegistrationSuccess.tsx
  src/pages/WaitingApproval.tsx
Labels: 🐞 Fix, 🔨 Refactor, 🎨 Design
