Repository Leets-Makers/Weeth-FE, pull requests merged in 2025-03, with the labels that each got.

#389 #377 Refactor: 기수 관련 UI 수정 및 추가 api 연결
  src/api/admin/cardinal/postCardinal.ts
  src/api/useGetCardinals.tsx
  src/components/Admin/Box.tsx
  src/components/Admin/ButtonGroup.tsx
  src/components/Admin/CardinalInfo.tsx
  src/components/Admin/CardinalSearchBar.tsx
  src/components/Admin/DirectCardinal.tsx
  src/components/Admin/Modal/CardinalEditModal.tsx
  src/components/Admin/Modal/CardinalModal.tsx
  src/components/Admin/Modal/CommonCardinalModal.tsx
  src/components/Admin/Modal/MemberDetailModal.tsx
  src/components/Admin/NavMenuList.tsx
  src/components/Admin/PenaltyListTable.tsx
  src/components/Admin/SearchBar.tsx
  src/components/Admin/SortButton.tsx
  src/components/Admin/context/MemberContext.tsx
  src/pages/admin/AdminPenalty.tsx
  src/styles/admin/cardinal/CardinalInfo.styled.ts
  src/styles/admin/cardinal/CardinalModal.styled.ts
  src/utils/admin/getHighestCardinal.ts
  src/utils/admin/handleNumericInput.ts
Labels: 🐞 Fix, ✨ Feat, 🔨 Refactor, 🎨 Design, 📬 API

#394 #392 feat: 멤버 디자인 수정
  src/assets/images/ic_BE_clip.svg
  src/assets/images/ic_DE_clip.svg
  src/assets/images/ic_FE_clip.svg
  src/components/MyPage/MyInfo.tsx
  src/components/common/CardinalTag.tsx
  src/pages/MemberDetail.tsx
Labels: 🎨 Design

#386 #379 Fix: qa 수정
  package-lock.json
  src/App.jsx
  src/api/admin/attendance/fetchAttendancesByCardinal.ts
  src/components/Admin/AttendDropdown.tsx
  src/components/Admin/Attendance.tsx
  src/components/Admin/Box.tsx
  src/components/Admin/Cardinal.tsx
  src/components/Admin/CardinalWrapper.tsx
  src/components/Admin/DuesInput.tsx
  src/components/Admin/DuesRegister.tsx
  src/components/Admin/DuesRegisterAdd.tsx
  src/components/Admin/DuesRegisterDropDown.tsx
  src/components/Admin/Expenditure.tsx
  src/components/Admin/ExpenditureRecord.tsx
  src/components/Admin/Modal/DuesModifyModal.tsx
  src/components/Admin/NavMenuList.tsx
  src/components/Admin/TotalDues.tsx
  src/pages/admin/AdminAttendance.tsx
  src/pages/admin/AdminDues.tsx
  src/styles/admin/AttendDropdown.styled.ts
  src/styles/admin/Attendance.styled.ts
  src/styles/admin/DuesRegisterAdd.styled.ts
  src/styles/admin/TotalDues.styled.ts
Labels: 🐞 Fix, 🔨 Refactor

#395 #393 feat: 일정 리스트 수정
  package-lock.json
  package.json
  src/api/useGetMonthSchedule.tsx
  src/components/Board/Comment.tsx
  src/components/Board/ReplyComment.tsx
  src/components/Calendar/MonthCalendar.tsx
  src/components/Calendar/ScheduleItem.tsx
  src/components/Event/EventContent.tsx
  src/components/Event/EventEditor.tsx
  src/components/Event/EventTitle.tsx
  src/components/Modal/DeleteModal.tsx
  src/components/home/HomeMain.tsx
  src/hooks/useCustomBack.tsx
  src/pages/BoardPostDetail.tsx
  src/pages/Calendar.tsx
  src/pages/Edit.tsx
  src/pages/EventDetail.tsx
  src/pages/MyPage.tsx
  src/pages/NoticePostDetail.tsx
  src/styles/calendar/MonthCalendar.styled.ts
Labels: 🐞 Fix, ✨ Feat, 🎨 Design

#388 #374 Refactor: 회비 페이지 리팩토링
  package-lock.json
  package.json
  public/pdfjs/pdf.mjs
  public/pdfjs/pdf.worker.mjs
  src/api/useGetDuesInfo.tsx
  src/components/Dues/DuesInfo.tsx
  src/components/Receipt/PdfViewer.tsx
  src/components/Receipt/ReceiptImageModal.tsx
  src/components/Receipt/ReceiptInfo.tsx
  src/components/Receipt/ReceiptMain.tsx
  src/components/Receipt/ReceiptPdfModal.tsx
  src/pages/Dues.tsx
  src/styles/dues/Dues.styled.ts
  src/styles/dues/DuesInfo.styled.ts
  src/styles/receipt/ReceiptInfo.styled.ts
  src/styles/receipt/ReceiptMain.styled.ts
Labels: 🐞 Fix, 🎨 Design

#397 #384 Fix: qa 수정
  src/assets/images/ic_eatmate.svg
  src/assets/images/ic_fling.svg
  src/assets/images/ic_gachtaxi.svg
  src/assets/images/ic_weneed.png
  src/assets/images/ic_yes.svg
  src/components/Board/Comment.tsx
  src/components/Board/CommentInput.tsx
  src/components/Board/PostCommentList.tsx
  src/components/Board/ReplyComment.tsx
  src/components/Event/EventEditor.tsx
  src/components/Event/EventTitle.tsx
  src/components/Modal/SelectModal.tsx
  src/components/home/HomeFooter.tsx
  src/components/home/HomeInfo.tsx
  src/components/home/HomeNotice.tsx
  src/pages/Board.tsx
  src/pages/BoardPostDetail.tsx
  src/pages/Edit.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/NoticePostDetail.tsx
  src/styles/board/Board.styled.ts
  src/styles/board/Comment.styled.ts
  src/styles/board/PostListItem.styled.ts
  src/styles/home/HomeInfo.styled.ts
Labels: 🐞 Fix, 🎨 Design

#391 #390 fix: 파일 업로드 수정
  src/api/editBoard.tsx
  src/api/editNotice.tsx
  src/api/postBoard.tsx
  src/api/postNotice.tsx
  src/api/useGetAllUsers.tsx
  src/api/useGetCardinals.tsx
  src/api/useGetGlobaluserInfo.tsx
  src/api/useGetMemberDetail.tsx
  src/api/useGetUserInfo.tsx
  src/api/usePatchMyInfo.tsx
  src/components/Board/FileUploader.tsx
  src/components/common/Loading.tsx
  src/pages/BoardPost.tsx
  src/pages/Edit.tsx
  src/pages/MemberDetail.tsx
  src/pages/NoticePostDetail.tsx
Labels: 🐞 Fix

#403 #401 feat: 로딩 컴포넌트 적용 및 디자인 수정
  package-lock.json
  package.json
  src/api/useGetAllUsers.tsx
  src/api/useGetMonthSchedule.tsx
  src/api/useGetUserInfo.tsx
  src/api/useGetYearlySchedule.tsx
  src/components/Calendar/MonthCalendar.tsx
  src/components/Calendar/ScheduleItem.tsx
  src/components/Calendar/YearCalendar.tsx
  src/components/Event/EventEditor.tsx
  src/components/Event/PickerModal.tsx
  src/components/Member/MemberList.tsx
  src/components/MyPage/MyInfo.tsx
  src/components/common/CardinalDropdown.tsx
  src/components/home/HomeInfo.tsx
  src/pages/Edit.tsx
  src/pages/Home.tsx
  src/pages/Member.tsx
  src/pages/MemberDetail.tsx
  src/styles/calendar/MonthCalendar.styled.ts
  src/styles/event/DatePicker.css
  src/styles/mypage/Mypage.styled.ts
Labels: ✨ Feat, 🎨 Design

#405 #402 feat: 파일 수정 구현
  src/App.jsx
  src/api/editBoard.tsx
  src/api/editNotice.tsx
  src/api/postBoard.tsx
  src/api/useGetBoardDetail.tsx
  src/pages/BoardNoticeEdit.tsx
  src/pages/BoardNoticePost.tsx
  src/pages/BoardPostDetail.tsx
  src/styles/board/BoardPost.styled.ts
  tsconfig.json
Labels: 🐞 Fix

#406 #399 Refactor:어드민 패널티 페이지 수정
  src/components/Admin/Box.tsx
  src/components/Admin/Button.tsx
  src/components/Admin/CardinalInfo.tsx
  src/components/Admin/CardinalSearchBar.tsx
  src/components/Admin/DuesRegister.tsx
  src/components/Admin/MemberListTable.tsx
  src/components/Admin/PenaltyAdd.tsx
  src/components/Admin/PenaltyDetail.tsx
  src/components/Admin/PenaltyListTable.tsx
  src/components/Admin/PenaltyMemberDropdown.tsx
  src/components/Admin/PenaltySubHeaderRow.tsx
  src/components/Admin/SearchBar.tsx
  src/components/Admin/TopBar.tsx
  src/pages/admin/AdminMember.tsx
  src/pages/admin/AdminPenalty.tsx
  src/styles/admin/AdminLayout.styled.ts
  src/styles/admin/penalty/Penalty.styled.ts
  src/styles/admin/penalty/PenaltyAdd.styled.ts
Labels: 🐞 Fix, ✨ Feat, 🔨 Refactor, 🎨 Design

#409 #407 feat: api 수정사항 반영
  src/App.jsx
  src/api/deletePost.tsx
  src/api/postBoard.tsx
  src/api/postComment.tsx
  src/api/useGetBoardDetail.tsx
  src/pages/Board.tsx
  src/pages/BoardDetail.tsx
  src/pages/NoticeDetail.tsx
Labels: 📬 API

#408 #396 Fix: api와 로딩 적용
  src/api/deleteComment.tsx
  src/api/deletePost.tsx
  src/api/patchAttend.tsx
  src/api/postComment.tsx
  src/api/useGetBoardDetail.tsx
  src/api/useGetBoardInfo.tsx
  src/api/useGetDuesInfo.tsx
  src/api/useGetPenalty.tsx
  src/assets/images/ic_default_position.svg
  src/components/Attendance/AttendCheckMain.tsx
  src/components/Attendance/AttendMain.tsx
  src/components/Attendance/Modal/ModalAttend.tsx
  src/components/Board/Comment.tsx
  src/components/Board/CommentInput.tsx
  src/components/Board/SlideNotice.tsx
  src/components/Receipt/ReceiptMain.tsx
  src/components/home/HomeInfo.tsx
  src/components/home/HomeNotice.tsx
  src/pages/Board.tsx
  src/pages/BoardDetail.tsx
  src/pages/Dues.tsx
  src/pages/Home.tsx
  src/pages/Notice.tsx
  src/pages/NoticeDetail.tsx
  src/styles/board/Comment.styled.ts
  src/styles/home/HomeInfo.styled.ts
Labels: 🐞 Fix, 🔨 Refactor

#412 #404 Fix: 2차 qa 수정
  package-lock.json
  src/api/admin/dues/adminReceipts.ts
  src/components/Admin/Cardinal.tsx
  src/components/Admin/DuesRegister.tsx
  src/components/Admin/DuesRegisterAdd.tsx
  src/pages/admin/AdminDues.tsx
  src/styles/admin/DuesRegisterAdd.styled.ts
  src/styles/admin/DuesRegisterDropDown.styled.ts
  src/styles/admin/TotalDues.styled.ts
Labels: 💻 Performance

#417 #411 Fix: 추가 qa 수정 - 다현
  src/api/admin/cardinal/postCardinal.ts
  src/api/admin/member/deleteUser.ts
  src/api/admin/member/getAdminUser.ts
  src/api/admin/member/patchUserManagement.ts
  src/api/admin/penalty/getPenalty.ts
  src/api/admin/penalty/modifyPenalty.ts
  src/components/Admin/MemberListTableHeader.tsx
  src/components/Admin/Modal/CardinalEditModal.tsx
  src/components/Admin/Modal/CommonModal.tsx
  src/components/Admin/Modal/MemberDetailModal.tsx
  src/components/Admin/PenaltyAdd.tsx
  src/components/Admin/PenaltyDetail.tsx
  src/components/Admin/PenaltyListTable.tsx
  src/components/Admin/PenaltySubHeaderRow.tsx
  src/components/Admin/SelectedTopBar.tsx
  src/components/Admin/context/MemberContext.tsx
  src/components/Admin/context/PenaltyReducer.ts
  src/pages/admin/AdminPenalty.tsx
  src/styles/admin/penalty/Penalty.styled.ts
Labels: 🐞 Fix, 🔨 Refactor, 🎨 Design

#419 #414 Fix: 어드민 회비 파일 확장자 qa 수정
  src/components/Admin/Cardinal.tsx
  src/components/Admin/DirectCardinal.tsx
  src/components/Admin/DuesRegisterAdd.tsx
  src/hooks/admin/handleFileChange.tsx
  src/pages/Home.tsx
  src/pages/admin/AdminMember.tsx
Labels: 🐞 Fix

#416 #410 Fix: 추가 qa 수정
  public/pdfjs/pdf.mjs
  public/pdfjs/pdf.worker.mjs
  src/api/useGetBoardDetail.tsx
  src/assets/images/ic_notion.svg
  src/components/Attendance/AttendCheckMain.tsx
  src/components/Attendance/AttendMain.tsx
  src/components/Attendance/Modal/ModalAttend.tsx
  src/components/Attendance/Modal/ModalPenalty.tsx
  src/components/Board/CommentInput.tsx
  src/components/Board/PostingButton.tsx
  src/components/Modal/SelectModal.tsx
  src/components/Receipt/PdfViewer.tsx
  src/components/Receipt/ReceiptMain.tsx
  src/components/Receipt/ReceiptPdfModal.tsx
  src/components/common/MenuModal.tsx
  src/components/common/Modal.tsx
  src/components/home/HomeFooter.tsx
  src/components/home/HomeNotice.tsx
  src/pages/Board.tsx
  src/pages/BoardDetail.tsx
  src/pages/Dues.tsx
  src/pages/Notice.tsx
  src/pages/NoticeDetail.tsx
  src/styles/attend/CommonModal.styled.ts
  src/styles/attend/ModalAttend.styled.ts
  src/styles/attend/ModalPenalty.styled.ts
  src/styles/board/Board.styled.ts
  src/styles/board/PostDetail.styled.ts
  src/styles/board/PostListItem.styled.ts
Labels: 🐞 Fix, 🔨 Refactor, 🎨 Design

#418 #413 fix: qa 수정 예진
  src/components/Admin/Box.tsx
  src/components/Admin/Button.tsx
  src/components/Admin/DuesInput.tsx
  src/components/Admin/DuesRegister.tsx
  src/components/Admin/Modal/CommonModal.tsx
  src/components/Admin/SearchBar.tsx
  src/components/Button/DropdownMenu.tsx
  src/components/Calendar/MonthCalendar.tsx
  src/components/Calendar/YearlyCard.tsx
  src/components/Dues/DueCategory.tsx
  src/components/Dues/DuesTitle.tsx
  src/components/Event/EventEditor.tsx
  src/components/Event/EventInput.tsx
  src/components/MyPage/InfoInput.tsx
  src/components/Signup/SignupDropDown.tsx
  src/components/Signup/SignupMemInput.tsx
  src/components/Signup/SignupTextComponent.tsx
  src/components/common/ToastMessage.tsx
  src/components/home/HomeNotice.tsx
  src/index.css
  src/pages/Edit.tsx
  src/pages/Member.tsx
  src/pages/MemberDetail.tsx
  src/styles/admin/AdminLayout.styled.ts
  src/styles/admin/AttendDropdown.styled.ts
  src/styles/admin/Attendance.styled.ts
  src/styles/admin/DuesRegisterAdd.styled.ts
  src/styles/admin/DuesRegisterDropDown.styled.ts
  src/styles/admin/ExpenditureRecord.styled.ts
  src/styles/admin/TotalDues.styled.ts
  src/styles/admin/penalty/Penalty.styled.ts
  src/styles/admin/penalty/PenaltyAdd.styled.ts
  src/styles/attend/AttendCheck.styled.ts
  src/styles/attend/AttendMain.styled.ts
  src/styles/attend/CommonModal.styled.ts
  src/styles/attend/ModalAttend.styled.ts
  src/styles/board/Board.styled.ts
  src/styles/board/BoardPost.styled.ts
  src/styles/board/Comment.styled.ts
  src/styles/board/PostDetail.styled.ts
  src/styles/board/PostListItem.styled.ts
  src/styles/calendar/DateInput.styled.ts
  src/styles/calendar/EventDetailTitle.styled.ts
  src/styles/calendar/ModalMonthContent.styled.ts
  src/styles/calendar/MonthCalendar.styled.ts
  src/styles/dues/Dues.styled.ts
  src/styles/dues/DuesInfo.styled.ts
  src/styles/event/EventAdmin.styled.ts
  src/styles/event/EventDetail.styled.ts
  src/styles/event/EventEditor.styled.ts
  src/styles/home/HomeInfo.styled.ts
  src/styles/member/Cardinal.styled.ts
  src/styles/member/MemberList.styled.ts
  src/styles/member/MemberName.styled.ts
  src/styles/mypage/Mypage.styled.ts
  src/styles/receipt/ReceiptInfo.styled.ts
  src/styles/receipt/ReceiptMain.styled.ts
Labels: 🐞 Fix, 📬 API

#438 #437 feat: 하이퍼링크 구현
  package-lock.json
  package.json
  src/components/Board/Comment.tsx
  src/components/Board/PostDetailMain.tsx
  src/components/Board/ReplyComment.tsx
  src/components/Event/EventContent.tsx
  src/components/Event/EventEditor.tsx
  src/hooks/convertLinksInText.tsx
  src/pages/BoardNoticePost.tsx
  src/styles/board/Comment.styled.ts
  src/styles/board/PostDetail.styled.ts
  src/styles/event/EventContent.styled.ts
Labels: ✨ Feat, 🎨 Design

#442 #439 Fix: 회비 오류 수정
  src/api/useGetDuesInfo.tsx
  src/pages/Dues.tsx
Labels: 🐞 Fix

#447 #446 Design: 디자인 추가
  src/assets/images/ic_PM.svg
  src/assets/images/ic_PM_clip.svg
  src/assets/images/ic_char_PM.svg
  src/assets/images/ic_char_PM_hover.svg
  src/assets/images/ic_register_success.svg
  src/assets/images/ic_waiting_approval.svg
  src/assets/images/logo/logo_full_Spring.svg
  src/components/Member/MemberItem.tsx
  src/components/MyPage/MyInfo.tsx
  src/components/home/HomeInfo.tsx
  src/hooks/setPositionIcon.tsx
  src/pages/Dues.tsx
  src/pages/Edit.tsx
  src/pages/Landing.tsx
  src/pages/MemberDetail.tsx
Labels: 🐞 Fix, 🎨 Design

#454 #453 fix: 추가 수정사항 반영
  src/components/Admin/AttendDropdown.tsx
  src/components/Event/EventTitle.tsx
  src/components/Member/MemberList.tsx
  src/components/common/Loading.tsx
  src/constants/departmentConstants.ts
  src/pages/BoardNoticeEdit.tsx
  src/pages/BoardNoticePost.tsx
  src/pages/EventDetail.tsx
  src/pages/NoticeDetail.tsx
  src/styles/board/Comment.styled.ts
Labels: 🐞 Fix, 🎨 Design

#458 #457 Feat: 어드민 회비 피드백 반영
  src/components/Admin/AttendDropdown.tsx
  src/components/Admin/Box.tsx
  src/components/Admin/TotalDues.tsx
Labels: 💻 Performance

#459 #415 feat: 캘린더 디자인 수정
  src/api/useGetMonthSchedule.tsx
  src/components/Calendar/MonthCalendar.tsx
  src/styles/calendar/MonthCalendar.styled.ts
Labels: ✨ Feat, 🎨 Design
